version: "3.8"
services:
    gateway:
        image: ${REGISTRY}/${LOGIN}/auction-gateway:${IMAGE_TAG}
        volumes:
            - /var/www/html:/var/www/html:ro
        ports:
            - "80:80"
            - "8080:8080"
            - "8081:8081"
            - "8082:8082"
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints: [node.role == manager]

    frontend:
        image: ${REGISTRY}/${LOGIN}/auction-frontend:${IMAGE_TAG}
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
        depends_on:
            - api

    api:
        image: ${REGISTRY}/${LOGIN}/auction-api:${IMAGE_TAG}
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            API_PORT: 8081
            SENTRY_DSN: ${SENTRY_DSN}
            POSTGRES_PASSWORD: qwerty
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_SSL_MODE: disable
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./secrets:/run/secrets:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 5s
        depends_on:
            - db
    db:
        image: ${REGISTRY}/${LOGIN}/auction-db:${IMAGE_TAG}
        environment:
            POSTGRES_PASSWORD: qwerty
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            #PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./.database/postgres/data:/var/lib/postgresql/data
            #- postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 5s
#volumes:
#    postgres-data:
#secrets:
#    sentry_dsn:
#        file: ./secrets/sentry_dsn.txt
