version: "3.7"
services:
    gateway:
        image: ${REGISTRY}/auction-testing-gateway:${IMAGE_TAG}

    frontend:
        image: ${REGISTRY}/auction-frontend:${IMAGE_TAG}

    api:
        image: ${REGISTRY}/auction-api:${IMAGE_TAG}

    api-php-fpm:
        image: ${REGISTRY}/auction-api-php-fpm:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USER: app
            MAILER_PASSWORD: secret
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://gateway:8080
            SENTRY_DSN: ""
            JWT_ENCRYPTION_KEY: secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        secrets:
            - jwt_public_key
            - jwt_private_key

    api-php-cli:
        image: ${REGISTRY}/auction-api-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USER: app
            MAILER_PASSWORD: secret
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://gateway:8080
            SENTRY_DSN: ""
            JWT_ENCRYPTION_KEY: secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        secrets:
            - jwt_public_key
            - jwt_private_key

    testing-api-php-cli:
        image: ${REGISTRY}/auction-testing-api-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USER: app
            MAILER_PASSWORD: secret
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://gateway:8080
            SENTRY_DSN: ""
            JWT_ENCRYPTION_KEY: secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        secrets:
            - jwt_public_key
            - jwt_private_key

    api-postgres:
        image: postgres:13.3-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app

    mailer:
        image: mailhog/mailhog

    cucumber-node-cli:
        image: ${REGISTRY}/auction-cucumber-node-cli:${IMAGE_TAG}
        volumes:
            - ./cucumber/var:/app/var

secrets:
    jwt_public_key:
        file: ./docker/development/secrets/jwt_public.key
    jwt_private_key:
        file: ./docker/development/secrets/jwt_private.key
