version: "3.8"
services:
    gateway:
        image: ${REGISTRY}/${LOGIN}/auction-gateway:${IMAGE_TAG}
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /var/www/html:/var/www/html:ro
        ports:
            - "80:80"
            - "443:443"
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints: [node.role == manager]

    frontend:
        image: ${REGISTRY}/${LOGIN}/auction-frontend:${IMAGE_TAG}
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s

    api:
        image: ${REGISTRY}/${LOGIN}/auction-api:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            API_PORT: 8081
            SENTRY_DSN: ${SENTRY_DSN}
        volumes:
            - ./secrets:/run/secrets:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 5s
#secrets:
#    sentry_dsn:
#        file: ./secrets/sentry_dsn.txt
